PREFIX ?= /usr/local
BINDIR ?= $(PREFIX)/bin
MANDIR ?= $(PREFIX)/share/man/man1
DOCDIR ?= $(PREFIX)/share/doc/ztrash
LICENSEDIR ?= $(PREFIX)/share/licenses/ztrash
BASHCOMPDIR ?= $(PREFIX)/share/bash-completion/completions
ZSHCOMPDIR ?= $(PREFIX)/share/zsh/site-functions
FISHCOMPDIR ?= $(PREFIX)/share/fish/vendor_completions.d

# scdoc renders the roff man page. Set SCDOC=scdoc, or leave it on PATH.
SCDOC ?= scdoc
SHELLS := bash zsh fish

# Read the version out of the script itself so there is a single source of
# truth. The assignment is not necessarily on the fifth line.
VERSION := $(shell sed -n 's/^VERSION="\(.*\)"$$/\1/p' ztrash | head -1)

.PHONY: all check test completions completions-check man install uninstall help

all: help

help:
	@echo "ztrash $(VERSION)"
	@echo ""
	@echo "  make check             run the zsh regression suite"
	@echo "  make completions       regenerate completions/ from the script"
	@echo "  make completions-check verify completions/ is up to date"
	@echo "  make man               render doc/ztrash.1.scd with scdoc"
	@echo "  make install           install into \$$DESTDIR\$$PREFIX"
	@echo "  make uninstall         remove an installed copy"
	@echo ""
	@echo "  PREFIX=$(PREFIX)  DESTDIR=$(DESTDIR)  SCDOC=$(SCDOC)"

# --- Tests ------------------------------------------------------------------

# The suite is dependency-free zsh; `check` is the conventional name.
check test:
	@zsh tests/run.zsh

# --- Completions ------------------------------------------------------------

# The shell completions are generated by the script itself so they can never
# drift from the option parser. Regenerating is a deliberate, reviewable diff.
completions:
	@for shell in $(SHELLS); do \
		zsh ./ztrash --print-completion $$shell > completions/ztrash.$$shell || exit 1; \
		echo "  regenerated completions/ztrash.$$shell"; \
	done

completions-check:
	@for shell in $(SHELLS); do \
		zsh ./ztrash --print-completion $$shell | diff -u - completions/ztrash.$$shell || exit 1; \
	done
	@echo "  completions are up to date"

# --- Man page ---------------------------------------------------------------

ztrash.1: doc/ztrash.1.scd
	@if command -v $(SCDOC) >/dev/null 2>&1; then \
		$(SCDOC) < $< > $@; \
		echo "  rendered $@"; \
	else \
		echo "error: $(SCDOC) not found. Install scdoc or set SCDOC=/path/to/scdoc." >&2; \
		echo "       doc/ztrash.1.scd is installable as-is if you prefer a source man page." >&2; \
		exit 1; \
	fi

man: ztrash.1

# --- Install ----------------------------------------------------------------

install:
	install -Dm755 ztrash $(DESTDIR)$(BINDIR)/ztrash
	install -Dm644 LICENSE $(DESTDIR)$(LICENSEDIR)/LICENSE
	install -Dm644 README.md $(DESTDIR)$(DOCDIR)/README.md
	install -Dm644 completions/ztrash.bash $(DESTDIR)$(BASHCOMPDIR)/ztrash
	install -Dm644 completions/ztrash.zsh $(DESTDIR)$(ZSHCOMPDIR)/_ztrash
	install -Dm644 completions/ztrash.fish $(DESTDIR)$(FISHCOMPDIR)/ztrash.fish
	@if command -v $(SCDOC) >/dev/null 2>&1; then \
		tmp=$$(mktemp) || exit 1; \
		if $(SCDOC) < doc/ztrash.1.scd > $$tmp; then \
			install -Dm644 $$tmp $(DESTDIR)$(MANDIR)/ztrash.1; \
		else \
			echo "error: $(SCDOC) failed to render doc/ztrash.1.scd" >&2; exit 1; \
		fi; \
		rm -f $$tmp; \
	else \
		echo "warning: $(SCDOC) not found; skipping the man page." >&2; \
		echo "         install doc/ztrash.1.scd by hand if you need one." >&2; \
	fi

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/ztrash
	rm -f $(DESTDIR)$(LICENSEDIR)/LICENSE
	rm -f $(DESTDIR)$(DOCDIR)/README.md
	rm -f $(DESTDIR)$(BASHCOMPDIR)/ztrash
	rm -f $(DESTDIR)$(ZSHCOMPDIR)/_ztrash
	rm -f $(DESTDIR)$(FISHCOMPDIR)/ztrash.fish
	rm -f $(DESTDIR)$(MANDIR)/ztrash.1
