complete -c ztrash -s l -l list -d 'List trash contents'
complete -c ztrash -s r -l restore -d 'Interactively restore items'
complete -c ztrash -s d -l delete -d 'Interactively delete items'
complete -c ztrash -s e -l empty -d 'Empty the trash'
complete -c ztrash -s s -l size -d 'Show trash size'
complete -c ztrash -s u -l undo -d 'Undo last trash'
complete -c ztrash -s w -l watch -d 'Watch trash size'
complete -c ztrash -s p -l purge -d 'Purge items older than N days' -r
complete -c ztrash -l fzf -d 'Fuzzy-find items'
complete -c ztrash -s v -l verbose -d 'Verbose output'
complete -c ztrash -s h -l help -d 'Show help'
complete -c ztrash -l version -d 'Show version'
complete -c ztrash -n '__fish_use_subcommand' -a restore -d 'Restore items matching a pattern'
complete -c ztrash -n '__fish_use_subcommand' -a find -d 'Search trashed items'
