complete -c ztrash -s l -l list -d 'List items in the trash'
complete -c ztrash -s r -l restore -d 'Interactively restore items'
complete -c ztrash -s d -l delete -d 'Interactively delete items'
complete -c ztrash -s e -l empty -d 'Empty the trash'
complete -c ztrash -s s -l size -d 'Show trash size'
complete -c ztrash -s u -l undo -d 'Restore the most recently trashed item'
complete -c ztrash -s w -l watch -d 'Live-updating trash size display'
complete -c ztrash -s p -l purge -d 'Purge items older than N days' -r
complete -c ztrash -l fzf -d 'Fuzzy-find items to restore or delete'
complete -c ztrash -l gc -d 'Remove orphaned trash entries'
complete -c ztrash -s y -l yes -d 'Assume yes, do not prompt'
complete -c ztrash -s n -l dry-run -d 'Show what would happen, change nothing'
complete -c ztrash -s v -l verbose -d 'Verbose output'
complete -c ztrash -l json -d 'Emit machine-readable JSON'
complete -c ztrash -l version -d 'Show version'
complete -c ztrash -s h -l help -d 'Show help'
complete -c ztrash -l print-completion -d 'Print a shell completion script' -r -f -a 'bash zsh fish'
complete -c ztrash -n '__fish_use_subcommand' -a restore -d 'Restore items matching a pattern'
complete -c ztrash -n '__fish_use_subcommand' -a find -d 'Search trashed items'
